mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(), name="create"),
    path('edit/', views.UserChangeView.as_view(), name="edit"),
    path('icon/', views.edit_profile_icon, name="icon"),
    path('password/', views.UserPasswordChangeView.as_view(), name="password"),
    path('accounts/', views.AccountsListView.as_view(), name="search_accounts"),
    path('@<str:username>/followings/',
         views.FollowingListView.as_view(), name="followings"),
    path('@<str:username>/followers/',
         views.FollowerListView.as_view(), name="followers"),
    path('@<str:username>/remove/', views.remove_view, name="remove"),
    path('@<str:username>/follow/', views.follow_view, name="follow"),
    path('@<str:username>/', views.user_profile_view, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'root'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('post.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/post/urls.py
from django.urls import path
from . import views


app_name = 'post'
urlpatterns = [
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    path('search/', views.SearchPostListView.as_view(), name='search'),
    path('replies/', views.ReplyPostListView.as_view(), name='replies'),
    path('status/<int:pk>/', views.PostStatusView.as_view(), name='status'),
    path('reply/<int:pk>/', views.reply_create_view, name='reply'),
    path('repost/<int:pk>/', views.repost_create_view, name='repost'),
    path('favorite/<int:pk>/', views.favorite_view, name='favorite'),
    path('delete/<int:pk>/', views.delete_view, name='delete'),
    path('favorited/<int:pk>/',
         views.LikedAccountsListView.as_view(), name='favorited'),
    path('', views.PostListView.as_view(), name='post_list'),
]

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang='ja'>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock title %} / Twitter-clone</title>
    {% block extra_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Twitter-clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-right" aria-controls="navbar-right" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-right">
                {% if request.user.is_authenticated  %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post:replies' %}">Reply</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post:search' %}">Tweet検索</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:search_accounts' %}">Accounts</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:profile' request.user.username %}">Profile({{ user.username }})</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post:post_create' %}">
                                <button class="btn btn-primary btn-sm" type="submit">ツイート</button>
                            </a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:create' %}">Create account</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    {% if messages %}
        <div class="container mt-2">
            <div class="row">
                <div class="my-div-style w-100">
                    <ul class="messages" style="list-style: none;">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}">
                            {% endif %}
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="container mt-2">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>