mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(), name="create"),
    path('edit/', views.UserChangeView.as_view(), name="edit"),
    path('icon/', views.edit_profile_icon, name="icon"),
    path('password/', views.UserPasswordChangeView.as_view(), name="password"),
    path('accounts/', views.AccountsListView.as_view(), name="search_accounts"),
    path('@<str:username>/followings/',
         views.FollowingListView.as_view(), name="followings"),
    path('@<str:username>/followers/',
         views.FollowerListView.as_view(), name="followers"),
    path('@<str:username>/remove/', views.remove_view, name="remove"),
    path('@<str:username>/follow/', views.follow_view, name="follow"),
    path('@<str:username>/', views.user_profile_view, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'root'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('post.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/post/urls.py
from django.urls import path
from . import views


app_name = 'post'
urlpatterns = [
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    path('search/', views.SearchPostListView.as_view(), name='search'),
    path('replies/', views.ReplyPostListView.as_view(), name='replies'),
    path('status/<int:pk>/', views.PostStatusView.as_view(), name='status'),
    path('reply/<int:pk>/', views.reply_create_view, name='reply'),
    path('repost/<int:pk>/', views.repost_create_view, name='repost'),
    path('favorite/<int:pk>/', views.favorite_view, name='favorite'),
    path('delete/<int:pk>/', views.delete_view, name='delete'),
    path('favorited/<int:pk>/',
         views.LikedAccountsListView.as_view(), name='favorited'),
    path('', views.PostListView.as_view(), name='post_list'),
]

mysite/accounts/models.py
import hashlib
import os.path
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):

        if not username:
            raise ValueError('The given username must be set')

        if not email:
            raise ValueError('The given email must be set')
        user = self.model(username=self.model.normalize_username(
            username), email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')

        return self._create_user(username, email, password, **extra_fields)


def get_image_path(instance, filename):
    return "%s%s" % (hashlib.sha1((instance.username + filename).encode('utf-8')).hexdigest(), os.path.splitext(filename)[1])


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField("ユーザー名", max_length=25, unique=True)
    email = models.EmailField("メールアドレス", unique=True)
    icon = models.ImageField(
        "アイコン", blank=True, null=True, upload_to=get_image_path)
    introduction = models.CharField(
        "自己紹介", max_length=75, blank=True, null=True)
    followers = models.ManyToManyField(
        'self', related_name='following', blank=True, symmetrical=False)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(default=timezone.now)
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

mysite/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.forms import ModelForm
from django import forms
from django.shortcuts import get_object_or_404


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label
            field.widget.attrs['class'] = 'form-control'


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label
            field.widget.attrs['class'] = 'form-control'


class UserChangeForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'introduction',
        )

    def __init__(self, username=None, email=None, introduction=None, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        if username:
            user = get_object_or_404(get_user_model(), username=username)
            super().__init__(instance=user, *args, **kwargs)
        else:
            super().__init__(*args, **kwargs)
        # ユーザーの更新前情報をフォームに挿入
        if username:
            self.fields['username'].widget.attrs['value'] = username
        if email:
            self.fields['email'].widget.attrs['value'] = email
        if introduction:
            self.fields['introduction'].widget.attrs['value'] = introduction
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label
            field.widget.attrs['class'] = 'form-control'

    def update(self, user):
        fields = []
        if user.username != self.cleaned_data['username']:
            user.username = self.cleaned_data['username']
            fields.append('username')
        if user.email != self.cleaned_data['email']:
            user.email = self.cleaned_data['email']
            fields.append('email')
        if user.introduction != self.cleaned_data['introduction']:
            user.introduction = self.cleaned_data['introduction']
            fields.append('introduction')
        user.save(update_fields=fields)


class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label
            field.widget.attrs['class'] = 'form-control'


class UpLoadProfileImgForm(forms.Form):
    icon = forms.ImageField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label
            field.widget.attrs['class'] = 'form-control'

mysite/accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
# Create your views here.
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.views.generic import TemplateView, CreateView, ListView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model, login, authenticate
from django.db.models import Count

from . import forms
from post.models import Post
from .forms import UpLoadProfileImgForm


class MyLoginView(LoginView):
    form_class = forms.LoginForm
    template_name = "accounts/login.html"

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'ログインしました。')
        return result


class MyLogoutView(LoginRequiredMixin, LogoutView):
    template_name = "accounts/logout.html"

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.warning(request, 'ログアウトしました。')
        return response


class IndexView(TemplateView):
    template_name = "accounts/index.html"


class UserCreateView(CreateView):
    form_class = forms.CustomUserCreationForm
    template_name = "accounts/create.html"
    success_url = reverse_lazy("post:post_list")

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'アカウントを作成しました。')
        username = form.cleaned_data.get("username")
        raw_pw = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=raw_pw)
        login(self.request, user)
        return result


class UserChangeView(LoginRequiredMixin, FormView):
    template_name = 'accounts/edit.html'
    form_class = forms.UserChangeForm

    def form_valid(self, form):
        # formのupdateメソッドにログインユーザーを渡して更新
        form.update(user=self.request.user)
        result = super().form_valid(form)
        messages.success(self.request, 'ユーザー情報を変更しました。')
        return result

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # 更新前のユーザー情報をkwargsとして渡す
        kwargs.update({
            'username': self.request.user.username,
            'email': self.request.user.email,
            'introduction': self.request.user.introduction,
        })
        return kwargs

    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=[self.request.user.username])


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = forms.UserPasswordChangeForm
    template_name = 'accounts/password_change.html'

    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=[self.request.user.username])

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'パスワードを変更しました。')
        return result


def user_profile_view(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    me = request.user
    followers = user.followers.all()
    is_following = request.user in followers
    follower_count = followers.count()
    followings = user.following.all()
    following_count = followings.count()
    post_list = Post.objects.filter(
        author__username=username).prefetch_related('liked_users').prefetch_related('replies').prefetch_related('reposted').order_by('-created_at').annotate(
            liked_count=Count("liked_users")).annotate(reply_count=Count("replies")).annotate(repost_count=Count("reposted"))
    liked = [None] * len(post_list)
    for i, post in enumerate(post_list):
        liked_users = post.liked_users
        liked[i] = me in liked_users.all()
    context = {
        'User': user,
        'zip': zip(post_list, liked),
        'is_following': is_following,
        'followers': followers,
        'follower_count': follower_count,
        'following_count': following_count,
    }
    if request.method == 'POST':
        pass
    return render(request, 'accounts/user_profile.html', context)


def remove_view(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user.followers.remove(request.user)
    user.save()
    messages.warning(request, 'リムーブしました。')
    return redirect(request.META['HTTP_REFERER'])


def follow_view(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user.followers.add(request.user)
    user.save()
    messages.success(request, 'フォローしました。')
    return redirect(request.META['HTTP_REFERER'])


def edit_profile_icon(request):
    if request.method != 'POST':
        form = UpLoadProfileImgForm()
    else:
        form = UpLoadProfileImgForm(request.POST, request.FILES)
        if form.is_valid():
            icon = form.cleaned_data['icon']
            user = request.user
            user.icon = icon
            user.save()
            messages.success(request, 'アイコンを変更しました。')
            return redirect('accounts:profile', user.username)
    context = {
        'form': form
    }
    return render(request, 'accounts/icon.html', context)


class AccountsListView(LoginRequiredMixin, ListView):
    template_name = 'accounts/account_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['followings'] = self.request.user.following.all()
        context['description'] = "ユーザー一覧"
        return context

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        qs = get_user_model().objects.all()
        if q_word:
            qs = qs.filter(username__contains=q_word)
        return qs


class FollowingListView(LoginRequiredMixin, ListView):
    template_name = 'accounts/account_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['followings'] = self.request.user.following.all()
        context['description'] = "@" + \
            self.kwargs.get('username', "") + "さんのフォロー一覧"
        return context

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        username = self.kwargs.get('username')
        qs = get_object_or_404(
            get_user_model(), username=username).following.all()
        if q_word:
            qs = qs.filter(username__contains=q_word)
        return qs


class FollowerListView(LoginRequiredMixin, ListView):
    template_name = 'accounts/account_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['followings'] = self.request.user.following.all()
        context['description'] = "@" + \
            self.kwargs.get('username', "") + "さんのフォロワー一覧"
        return context

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        username = self.kwargs.get('username', "")
        qs = get_object_or_404(
            get_user_model(), username=username).followers.all()
        if q_word:
            qs = qs.filter(username__contains=q_word)
        return qs

mysite/accounts/templates/accounts/account_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ description }}{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated  %}
        {% if description %}
            <h2>{{ description }}</h2>
        {% endif %}
        <div class="" id="users">
            <form class="d-flex" action="" method="get" name="search">
                <input class="form-control w-50" name="query" value="{{ request.GET.query }}" type="text" placeholder="ユーザー検索">
                <button class="btn btn-outline-success w-10" type="submit">検索</button>
            </form>
            {% for user in user_list %}
                <ul class="list-unstyled">
                    <div class="row mt-2 border">
                        <div style="width: 100px;" class="col-2 my-1">
                            <a href={% url 'accounts:profile' user.username %}>
                                {% if user.icon %}
                                    <img class="align-self-center img-thumbnail" src="{{ user.icon.url }}" width="100" height="100">
                                {% else %}
                                    <img class="align-self-center img-thumbnail" src="{% static 'images/user_icon.png' %}" width="100" height="100">
                                {% endif %}
                            </a>
                        </div>
                        <div class="col my-1">
                            <h4 class=""><a class="text-dark" href={% url 'accounts:profile' user.username %}>@{{ user }}</a></h4>
                            <p class="text-break">
                                {% if user.introduction %}
                                    {{ user.introduction | linebreaksbr | urlize }}
                                {% endif %}
                            </p>
                        </div>
                        <div style="width: 150px;" class="col-2 my-1">
                            <a href={% url 'accounts:profile' user.username %}>
                                {% if user == request.user %}
                                {% elif user in followings %}
                                    <a href="{% url "accounts:remove" user.username %}" type="submit" class="btn btn-outline-primary" id="remove">フォロー解除</a>
                                {% else %}
                                    <a href="{% url "accounts:follow" user.username %}" type="submit" class="btn btn-primary" id="follow">フォローする</a>
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </ul>
            {% empty %}
                <h6 class="mt-2">ユーザーが見つかりませんでした</h6>
            {% endfor %}
        </div>
    {% else %}
        <h6>ようこそTwitter-cloneへ！<a href="{% url 'accounts:create' %}">アカウントを作成する</a>か<a href="{% url 'accounts:login' %}">ログイン</a>してください</h6>
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var q = document.search.query;
        var len = q.value.length;
        q.focus();
        q.setSelectionRange(len, len);
    </script>
{% endblock %}

mysite/accounts/templates/accounts/create.html
{% extends 'base.html' %}
{% block title %}新規ユーザーの作成{% endblock title %}
{% block content %}
    <p>新規ユーザーの作成</p>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-sm">作成</button>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{% block title %}ユーザー情報の編集{% endblock title %}
{% block content %}
    <p>ユーザー情報の編集</p>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-sm">変更</button>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/icon.html
{% extends 'base.html' %}
{% block title %}アイコンの編集{% endblock title %}
{% block content %}
    <p>アイコンの編集</p>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.icon }}{{ form.icon.errors }}
        <div class="mt-3" id="btn">
            <button type="submit" class="btn btn-primary btn-sm">変更</button>
        </div>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block title %}メインページ{% endblock title %}
{% block content %}
    <h1>メインページ</h1>
{% endblock %}

mysite/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}ログイン{% endblock title %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-sm">ログイン</button>
{% endblock %}

mysite/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block title %}ログアウト{% endblock title %}
{% block content %}
    <form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">ログアウト</button>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% block title %}パスワードの変更{% endblock title %}
{% block content %}
    <p>パスワードの変更</p>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-sm">変更</button>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}@{{ User.username }}{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-3 p-1 border rounded" id="user_status">
            <div class="container-fluid">
                {% if User.icon %}
                    <img class="img-thumbnail" src="{{ User.icon.url }}">
                {% else %}
                    <img class="img-thumbnail" src="{% static 'images/user_icon.png' %}">
                {% endif %}
            </div>
            <div class="container-fluid mt-2 text-break" id="username">
                <h2>@{{ User.username }}</h2>
            </div>
            <div class="container-fluid mt-3 text-break" id="bio">
                {% if User.introduction %}
                    <h6>{{ User.introduction | linebreaksbr | urlize }}</h6>
                {% endif %}
            </div>
            <div class="container-fluid mt-3" id="following_count">
                <a class="text-dark" href="{% url "accounts:followings" User.username %}"><h6>フォロー {{ following_count }}人</h6></a>
                <a class="text-dark" href="{% url "accounts:followers" User.username %}"><h6>フォロワー {{ follower_count }}人</h6></a>
            </div>
            <div class="container-fluid mt-3">
                {% if User.username == request.user.username %}
                    <a href="{% url "accounts:edit" %}" type="submit" class="btn btn-info w-100" id="edit">プロフィール編集</a>
                    <a href="{% url "accounts:icon" %}" type="submit" class="btn btn-info w-100 mt-1" id="icon_edit">アイコン変更</a>
                    <a href="{% url "accounts:password" %}" type="submit" class="btn btn-outline-info w-100 mt-1" id="password_edit">パスワード変更</a>
                {% elif is_following %}
                    <a href="{% url "accounts:remove" User.username %}" type="submit" class="btn btn-outline-primary" id="remove">フォロー解除</a>
                {% else %}
                    <a href="{% url "accounts:follow" User.username %}" type="submit" class="btn btn-primary" id="follow">フォローする</a>
                {% endif %}
            </div>
        </div>
        <div class="col-9 p-3" id="user_post">
            <h2>@{{ User.username }}さんのTweet一覧</h2>
            {% for post, liked in zip %}
                <ul class="list-unstyled">
                    <div class="row mt-2 border">
                        <div style="width: 100px;" class="col-2 my-1">
                            <a href={% url 'accounts:profile' post.author.username %}>
                                {% if post.author.icon %}
                                    <img class="align-self-center img-thumbnail" src="{{ post.author.icon.url }}" width="100" height="100">
                                {% else %}
                                    <img class="align-self-center img-thumbnail" src="{% static 'images/user_icon.png' %}" width="100" height="100">
                                {% endif %}
                            </a>
                        </div>
                        <div class="col my-1">
                            <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.author.username %}>@{{ post.author }}</a></h4>
                            <p class="text-break">
                                {{ post.content | linebreaksbr | urlize }}
                            </p>
                            {% if post.repost_parent %}
                                <div class="row my-2 border">
                                    <div style="width: 100px;" class="col-2 my-1">
                                        <a href={% url 'accounts:profile' post.repost_parent.author.username %}>
                                            {% if post.repost_parent.author.icon %}
                                                <img class="align-self-center img-thumbnail img-fluid" src="{{ post.repost_parent.author.icon.url }}">
                                            {% else %}
                                                <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                                            {% endif %}
                                        </a>
                                    </div>
                                    <div class="col my-1">
                                        <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.repost_parent.author.username %}>@{{ post.repost_parent.author }}</a></h4>
                                        <p class="text-break">
                                            {{ post.repost_parent.content | linebreaksbr | urlize }}
                                        </p>
                                        <a href="{% url "post:status" post.repost_parent.pk %}" class="d-inline-block text-muted ms-2">
                                            <h6 class="">{{ post.repost_parent.created_at }}</h6>
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                            <a href="{% url "post:reply" post.pk %}" class="d-inline-block">
                                <button type="button" class="btn btn-primary btn-sm">返信{% if post.reply_count %}  {{ post.reply_count }}{% endif %}</button>
                            </a>
                            <a href="{% url "post:repost" post.pk %}" class="d-inline-block">
                                <button type="button" class="btn btn-outline-success btn-sm">リツイート{% if post.repost_count %} {{ post.repost_count }}{% endif %}</button>
                            </a>
                            <a href="{% url "post:favorite" post.pk %}" class="d-inline-block">
                                {% if liked %}<button type="button" class="btn btn-warning btn-sm">{% else %}<button type="button" class="btn btn-outline-warning btn-sm">{% endif %}
                                    ☆いいね{% if post.liked_count %} {{ post.liked_count }}{% endif %}
                                </button>
                            </a>
                            {% if post.author == request.user %}
                                <a href="{% url "post:delete" post.pk %}" class="d-inline-block">
                                    <button type="button" class="btn btn-outline-danger btn-sm">削除</button>
                                </a>
                            {% endif %}
                            <a href="{% url "post:status" post.pk %}" class="d-inline-block text-muted ms-2">
                                <h6 class="">{{ post.created_at }}</h6>
                            </a>
                        </div>
                    </div>
                </ul>
            {% empty %}
                <h5>Tweetがまだありません</h5>
            {% endfor %}
        </div>
    </div>
{% endblock %}