mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(), name="create"),
    path('edit/', views.UserChangeView.as_view(), name="edit"),
    path('icon/', views.edit_profile_icon, name="icon"),
    path('password/', views.UserPasswordChangeView.as_view(), name="password"),
    path('accounts/', views.AccountsListView.as_view(), name="search_accounts"),
    path('@<str:username>/followings/',
         views.FollowingListView.as_view(), name="followings"),
    path('@<str:username>/followers/',
         views.FollowerListView.as_view(), name="followers"),
    path('@<str:username>/remove/', views.remove_view, name="remove"),
    path('@<str:username>/follow/', views.follow_view, name="follow"),
    path('@<str:username>/', views.user_profile_view, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'root'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('post.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/post/urls.py
from django.urls import path
from . import views


app_name = 'post'
urlpatterns = [
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    path('search/', views.SearchPostListView.as_view(), name='search'),
    path('replies/', views.ReplyPostListView.as_view(), name='replies'),
    path('status/<int:pk>/', views.PostStatusView.as_view(), name='status'),
    path('reply/<int:pk>/', views.reply_create_view, name='reply'),
    path('repost/<int:pk>/', views.repost_create_view, name='repost'),
    path('favorite/<int:pk>/', views.favorite_view, name='favorite'),
    path('delete/<int:pk>/', views.delete_view, name='delete'),
    path('favorited/<int:pk>/',
         views.LikedAccountsListView.as_view(), name='favorited'),
    path('', views.PostListView.as_view(), name='post_list'),
]

mysite/post/models.py
from django.db import models

# Create your models here.

from django.contrib.auth import get_user_model


class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), verbose_name='author',
                               on_delete=models.CASCADE)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='replies',
                               on_delete=models.SET_NULL)
    liked_users = models.ManyToManyField(
        get_user_model(), related_name='favorite_posts', blank=True, symmetrical=False)
    repost_parent = models.ForeignKey('self', blank=True, null=True, related_name='reposted',
                                      on_delete=models.SET_NULL)

    def __str__(self):
        return self.content

mysite/post/forms.py
from django import forms
from .models import Post


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = "いまどうしてる？"
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs[
                'onkeydown'] = "if(event.ctrlKey&&event.keyCode==13){document.getElementById('submit').click();return false};"

mysite/post/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.db.models import Q, Count
from itertools import chain
from .models import Post
from . import forms


class PostListView(LoginRequiredMixin, ListView):
    template_name = 'post/post_list.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['User'] = user
        post_list = Post.objects.filter(author__in=chain(user.following.all(), [user])).prefetch_related(
            'liked_users').prefetch_related('replies').prefetch_related('reposted').order_by('-created_at').annotate(
                liked_count=Count("liked_users")).annotate(reply_count=Count("replies")).annotate(repost_count=Count("reposted"))
        context['description'] = 'タイムライン'
        liked = [None] * len(post_list)
        for i, post in enumerate(post_list):
            liked[i] = user in post.liked_users.all()
        context['zip'] = zip(post_list, liked)
        return context

    def get_queryset(self):
        user = self.request.user
        qs = Post.objects.filter(author__in=chain(
            user.following.all(), [user])).order_by('-created_at').annotate(
                liked_count=Count("liked_users")).annotate(reply_count=Count("replies")).annotate(repost_count=Count("reposted"))
        return qs


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = forms.PostCreationForm
    template_name = "post/post_create.html"
    success_url = reverse_lazy("post:post_list")
    description = "ツイートの作成"

    def form_valid(self, form):
        form.instance.author = self.request.user
        result = super().form_valid(form)
        messages.success(self.request, 'ツイートしました。')
        return result


def favorite_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user
    already_liked = user in post.liked_users.all()
    if already_liked:
        post.liked_users.remove(user)
        messages.warning(request, 'いいねを取り消しました。')
    else:
        post.liked_users.add(user)
        messages.success(request, 'いいねしました。')
    post.save()
    return redirect(request.META['HTTP_REFERER'])


def delete_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author == request.user:
        post.delete()
        messages.warning(request, 'ツイートを削除しました。')
    return redirect(request.META['HTTP_REFERER'])


class SearchPostListView(LoginRequiredMixin, ListView):
    template_name = 'post/search_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['User'] = user
        post_list = context['post_list']
        liked = [None] * len(post_list)
        for i, post in enumerate(post_list):
            liked_users = post.liked_users
            liked[i] = user in liked_users.all()
        context['zip'] = zip(post_list, liked)
        return context

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        qs = Post.objects.all().prefetch_related('liked_users').order_by(
            '-created_at').annotate(liked_count=Count("liked_users")).annotate(reply_count=Count("replies")).annotate(repost_count=Count("reposted"))
        if q_word:
            qs = qs.filter(content__contains=q_word)
        return qs


class PostStatusView(DetailView):
    template_name = 'post/post_status.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['User'] = user
        context['pk'] = self.kwargs.get('pk')
        post = get_object_or_404(Post, pk=context['pk'])
        parent = post.parent
        if parent:
            context['parent_post'] = parent
            liked_users = parent.liked_users
            context['parent_liked'] = user in liked_users.all()
            context['parent_likes'] = liked_users.count()
            context['parent_reply_count'] = parent.replies.count()
            context['parent_repost_count'] = parent.reposted.count()
        else:
            context['parent_post'] = None
        context['post'] = post
        liked_users = post.liked_users
        context['likes'] = liked_users.count()
        context['reply_count'] = post.replies.count()
        context['repost_count'] = post.reposted.count()
        liked_users = post.liked_users
        context['liked'] = user in liked_users.all()
        reply_list = (post.replies.all() | post.reposted.all()
                      ).prefetch_related('liked_users').prefetch_related('replies').prefetch_related('reposted').annotate(
            liked_count=Count("liked_users")).annotate(reply_count=Count("replies")).annotate(repost_count=Count("reposted"))
        reply_liked = [None] * len(reply_list)
        for i, reply in enumerate(reply_list):
            liked_users = reply.liked_users
            reply_liked[i] = user in liked_users.all()
        context['zip'] = zip(reply_list, reply_liked)
        return context


def reply_create_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = forms.PostCreationForm(request.POST or None)
    description = "返信の作成"
    if request.method == 'POST':
        reply = form.save(commit=False)
        reply.author = request.user
        reply.parent = post
        reply.content = "@" + reply.parent.author.username + " " + reply.content
        reply.save()
        messages.success(request, '返信しました。')
        return redirect('post:post_list')

    context = {
        'form': form,
        'post': post,
        'description': description,
    }
    return render(request, 'post/post_create.html', context)


class ReplyPostListView(LoginRequiredMixin, ListView):
    template_name = 'post/reply_list.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['User'] = user
        post_list = context['post_list']
        liked = [False] * len(post_list)
        for i, post in enumerate(post_list):
            liked_users = post.liked_users
            liked[i] = user in liked_users.all()
        context['zip'] = zip(post_list, liked)
        return context

    def get_queryset(self):
        username = self.request.user.username
        qs = Post.objects.filter(
            Q(content__contains="@" + username + " ") |
            Q(content__contains="@" + username + "　") |
            Q(content__contains="@" + username + "\n") |
            Q(content__contains="@" + username + "\r") |
            Q(content__endswith="@" + username)
        ).prefetch_related('liked_users').order_by('-created_at').annotate(liked_count=Count("liked_users")).annotate(reply_count=Count("replies")).annotate(repost_count=Count("reposted"))
        return qs


class LikedAccountsListView(LoginRequiredMixin, ListView):
    template_name = 'accounts/account_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['followings'] = self.request.user.following.all()
        context['description'] = "いいねしたユーザー一覧"
        return context

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        qs = post.liked_users.all().prefetch_related('following')
        if q_word:
            qs = qs.filter(username__contains=q_word)
        return qs


def repost_create_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = forms.PostCreationForm(request.POST or None)
    description = "リツイートの作成"
    if request.method == 'POST':
        repost = form.save(commit=False)
        repost.author = request.user
        repost.repost_parent = post
        repost.save()
        messages.success(request, 'リツイートしました。')
        return redirect('post:post_list')

    context = {
        'form': form,
        'post': post,
        'description': description,
    }
    return render(request, 'post/post_create.html', context)

mysite/post/templates/post/post_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ description }}{% endblock title %}
{% block content %}
    {% if post %}
        <div class="row mt-2 border">
            <div style="width: 100px;" class="col-2 my-1">
                {% if post.author.icon %}
                    <img class="align-self-center img-thumbnail img-fluid" src="{{ post.author.icon.url }}">
                {% else %}
                    <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                {% endif %}
            </div>
            <div class="col my-1">
                <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.author.username %}>@{{ post.author }}</a></h4>
                <p class="text-break">
                    {{ post.content | linebreaksbr | urlize }}
                </p>
                <h6 class="d-inline-block text-muted ms-2">{{ post.created_at }}</h6>
            </div>
        </div>
    {% endif %}
    <p>{{ description }}</p>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="submit" class="btn btn-primary btn-sm mt-2">Tweet</button>
    </form>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var q = document.getElementById('id_content');
        var len = q.value.length;
        q.focus();
        q.setSelectionRange(len, len);
    </script>
{% endblock %}

mysite/post/templates/post/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}タイムライン{% endblock title %}
{% block content %}
    {% if request.user.is_authenticated  %}
        {% for post, liked in zip %}
            <ul class="list-unstyled">
                <div class="row mt-2 border">
                    <div style="width: 100px;" class="col-2 my-1">
                        <a href={% url 'accounts:profile' post.author.username %}>
                            {% if post.author.icon %}
                                <img class="align-self-center img-thumbnail img-fluid" src="{{ post.author.icon.url }}">
                            {% else %}
                                <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col my-1">
                        <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.author.username %}>@{{ post.author }}</a></h4>
                        <p class="text-break">
                            {{ post.content | linebreaksbr | urlize }}
                        </p>
                        {% if post.repost_parent %}
                            <div class="row my-2 border">
                                <div style="width: 100px;" class="col-2 my-1">
                                    <a href={% url 'accounts:profile' post.repost_parent.author.username %}>
                                        {% if post.repost_parent.author.icon %}
                                            <img class="align-self-center img-thumbnail img-fluid" src="{{ post.repost_parent.author.icon.url }}">
                                        {% else %}
                                            <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="col my-1">
                                    <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.repost_parent.author.username %}>@{{ post.repost_parent.author }}</a></h4>
                                    <p class="text-break">
                                        {{ post.repost_parent.content | linebreaksbr | urlize }}
                                    </p>
                                    <a href="{% url "post:status" post.repost_parent.pk %}" class="d-inline-block text-muted ms-2">
                                        <h6 class="">{{ post.repost_parent.created_at }}</h6>
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                        <a href="{% url "post:reply" post.pk %}" class="d-inline-block">
                            <button type="button" class="btn btn-primary btn-sm">返信{% if post.reply_count %}  {{ post.reply_count }}{% endif %}</button>
                        </a>
                        <a href="{% url "post:repost" post.pk %}" class="d-inline-block">
                            <button type="button" class="btn btn-outline-success btn-sm">リツイート{% if post.repost_count %} {{ post.repost_count }}{% endif %}</button>
                        </a>
                        <a href="{% url "post:favorite" post.pk %}" class="d-inline-block">
                            {% if liked %}<button type="button" class="btn btn-warning btn-sm">{% else %}<button type="button" class="btn btn-outline-warning btn-sm">{% endif %}
                                ☆いいね{% if post.liked_count %} {{ post.liked_count }}{% endif %}
                            </button>
                        </a>
                        {% if post.author == request.user %}
                            <a href="{% url "post:delete" post.pk %}" class="d-inline-block">
                                <button type="button" class="btn btn-outline-danger btn-sm">削除</button>
                            </a>
                        {% endif %}
                        <a href="{% url "post:status" post.pk %}" class="d-inline-block text-muted ms-2">
                            <h6 class="">{{ post.created_at }}</h6>
                        </a>
                    </div>
                </div>
            </ul>
        {% empty %}
            <h6>Tweetがまだありません</h6>
        {% endfor %}
    {% else %}
        <h6>ようこそTwitter-cloneへ！<a href="{% url 'accounts:create' %}">アカウントを作成する</a>か<a href="{% url 'accounts:login' %}">ログイン</a>してください</h6>
    {% endif %}
{% endblock %}

mysite/post/templates/post/reply_list.html
{% extends 'base.html' %}
{% load static %}
{% load boost %}

{% block title %}返信一覧{% endblock title %}
{% block content %}
    {% if request.user.is_authenticated  %}
        {% for post, liked in zip %}
            <ul class="list-unstyled">
                <div class="row mt-2 border">
                    <div style="width: 100px;" class="col-2 my-1">
                        <a href={% url 'accounts:profile' post.author.username %}>
                            {% if post.author.icon %}
                                <img class="align-self-center img-thumbnail img-fluid" src="{{ post.author.icon.url }}">
                            {% else %}
                                <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col my-1">
                        <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.author.username %}>@{{ post.author }}</a></h4>
                        <p class="text-break">
                            {{ post.content | linebreaksbr | urlize }}
                        </p>
                        {% if post.repost_parent %}
                            <div class="row my-2 border">
                                <div style="width: 100px;" class="col-2 my-1">
                                    <a href={% url 'accounts:profile' post.repost_parent.author.username %}>
                                        {% if post.repost_parent.author.icon %}
                                            <img class="align-self-center img-thumbnail img-fluid" src="{{ post.repost_parent.author.icon.url }}">
                                        {% else %}
                                            <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="col my-1">
                                    <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.repost_parent.author.username %}>@{{ post.repost_parent.author }}</a></h4>
                                    <p class="text-break">
                                        {{ post.repost_parent.content | linebreaksbr | urlize }}
                                    </p>
                                    <a href="{% url "post:status" post.repost_parent.pk %}" class="d-inline-block text-muted ms-2">
                                        <h6 class="">{{ post.repost_parent.created_at }}</h6>
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                        <a href="{% url "post:reply" post.pk %}" class="d-inline-block">
                            <button type="button" class="btn btn-primary btn-sm">返信{% if reply_count %}  {{ reply_count }}{% endif %}</button>
                        </a>
                        <a href="{% url "post:repost" post.pk %}" class="d-inline-block">
                            <button type="button" class="btn btn-outline-success btn-sm">リツイート{% if repost_count %} {{ repost_count }}{% endif %}</button>
                        </a>
                        <a href="{% url "post:favorite" post.pk %}" class="d-inline-block">
                            {% if liked %}<button type="button" class="btn btn-warning btn-sm">{% else %}<button type="button" class="btn btn-outline-warning btn-sm">{% endif %}
                                ☆いいね{% if post.liked_count %} {{ post.liked_count }}{% endif %}
                            </button>
                        </a>
                        {% if post.author == request.user %}
                            <a href="{% url "post:delete" post.pk %}" class="d-inline-block">
                                <button type="button" class="btn btn-outline-danger btn-sm">削除</button>
                            </a>
                        {% endif %}
                        <a href="{% url "post:status" post.pk %}" class="d-inline-block text-muted ms-2">
                            <h6 class="">{{ post.created_at }}</h6>
                        </a>
                    </div>
                </div>
            </ul>
        {% empty %}
            <h6 class="mt-2">返信が見つかりませんでした</h6>
        {% endfor %}
    {% else %}
        <h6>ようこそTwitter-cloneへ！<a href="{% url 'accounts:create' %}">アカウントを作成する</a>か<a href="{% url 'accounts:login' %}">ログイン</a>してください</h6>
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var q = document.search.query;
        var len = q.value.length;
        q.focus();
        q.setSelectionRange(len, len);
    </script>
{% endblock %}

mysite/post/templates/post/search_list.html
{% extends 'base.html' %}
{% load static %}
{% load boost %}

{% block title %}ツイート検索{% endblock title %}
{% block content %}
    {% if request.user.is_authenticated  %}
        <form class="d-flex" action="" method="get" name="search">
            <input class="form-control w-50" name="query" value="{{ request.GET.query }}" type="text" placeholder="ツイート検索">
            <button class="btn btn-outline-success w-10" type="submit">検索</button>
        </form>
        {% for post, liked in zip %}
            <ul class="list-unstyled">
                <div class="row mt-2 border">
                    <div style="width: 100px;" class="col-2 my-1">
                        <a href={% url 'accounts:profile' post.author.username %}>
                            {% if post.author.icon %}
                                <img class="align-self-center img-thumbnail img-fluid" src="{{ post.author.icon.url }}">
                            {% else %}
                                <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col my-1">
                        <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.author.username %}>@{{ post.author }}</a></h4>
                        <p class="text-break">
                            {{ post.content | linebreaksbr | urlize }}
                        </p>
                        {% if post.repost_parent %}
                            <div class="row my-2 border">
                                <div style="width: 100px;" class="col-2 my-1">
                                    <a href={% url 'accounts:profile' post.repost_parent.author.username %}>
                                        {% if post.repost_parent.author.icon %}
                                            <img class="align-self-center img-thumbnail img-fluid" src="{{ post.repost_parent.author.icon.url }}">
                                        {% else %}
                                            <img class="align-self-center img-thumbnail img-fluid" src="{% static 'images/user_icon.png' %}">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="col my-1">
                                    <h4 class=""><a class="text-dark" href={% url 'accounts:profile' post.repost_parent.author.username %}>@{{ post.repost_parent.author }}</a></h4>
                                    <p class="text-break">
                                        {{ post.repost_parent.content | linebreaksbr | urlize }}
                                    </p>
                                    <a href="{% url "post:status" post.repost_parent.pk %}" class="d-inline-block text-muted ms-2">
                                        <h6 class="">{{ post.repost_parent.created_at }}</h6>
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                        <a href="{% url "post:reply" post.pk %}" class="d-inline-block">
                            <button type="button" class="btn btn-primary btn-sm">返信{% if post.reply_count %}  {{ post.reply_count }}{% endif %}</button>
                        </a>
                        <a href="{% url "post:repost" post.pk %}" class="d-inline-block">
                            <button type="button" class="btn btn-outline-success btn-sm">リツイート{% if post.repost_count %} {{ post.repost_count }}{% endif %}</button>
                        </a>
                        <a href="{% url "post:favorite" post.pk %}" class="d-inline-block">
                            {% if liked %}<button type="button" class="btn btn-warning btn-sm">{% else %}<button type="button" class="btn btn-outline-warning btn-sm">{% endif %}
                                ☆いいね{% if post.liked_count %} {{ post.liked_count }}{% endif %}
                            </button>
                        </a>
                        {% if post.author == request.user %}
                            <a href="{% url "post:delete" post.pk %}" class="d-inline-block ms-2">
                                <button type="button" class="btn btn-outline-danger btn-sm">削除</button>
                            </a>
                        {% endif %}
                        <a href="{% url "post:status" post.pk %}" class="d-inline-block text-muted ms-2">
                            <h6 class="">{{ post.created_at }}</h6>
                        </a>
                    </div>
                </div>
            </ul>
        {% empty %}
            <h6 class="mt-2">Tweetが見つかりませんでした</h6>
        {% endfor %}
    {% else %}
        <h6>ようこそTwitter-cloneへ！<a href="{% url 'accounts:create' %}">アカウントを作成する</a>か<a href="{% url 'accounts:login' %}">ログイン</a>してください</h6>
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var q = document.search.query;
        var len = q.value.length;
        q.focus();
        q.setSelectionRange(len, len);
    </script>
{% endblock %}